"""create government tables

Revision ID: 0e6dc52d15fc
Revises: 
Create Date: 2026-09-16 00:48:03.557637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0e6dc52d15fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_bills',
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('bill_type', sa.String(length=20), nullable=False),
    sa.Column('congress_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('short_title', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('chamber', sa.String(length=20), nullable=False),
    sa.Column('policy_area', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('introduced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sponsor_bioguide_id', sa.String(length=20), nullable=True),
    sa.Column('sponsor_name', sa.String(length=200), nullable=True),
    sa.Column('sponsor_party', sa.String(length=50), nullable=True),
    sa.Column('sponsor_state', sa.String(length=2), nullable=True),
    sa.Column('sponsor_chamber', sa.String(length=20), nullable=True),
    sa.Column('cosponsors_count', sa.Integer(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=True, comment='Full action history as JSON array'),
    sa.Column('committees', sa.JSON(), nullable=True, comment='Committee names this bill was referred to'),
    sa.Column('related_bills', sa.JSON(), nullable=True, comment='Related bill numbers'),
    sa.Column('subjects', sa.JSON(), nullable=True, comment='Legislative subject tags'),
    sa.Column('affected_sectors', sa.JSON(), nullable=True, comment='Market sectors affected by this bill'),
    sa.Column('affected_tickers', sa.JSON(), nullable=True, comment='Stock tickers likely affected'),
    sa.Column('market_sentiment', sa.String(length=10), nullable=True, comment='bullish, bearish, or neutral'),
    sa.Column('market_reasoning', sa.Text(), nullable=True, comment='AI explanation of market impact'),
    sa.Column('market_confidence', sa.Float(), nullable=True, comment='AI confidence score 0 to 1'),
    sa.Column('raw_data', sa.JSON(), nullable=True, comment='Original GovTrack API response'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='US Congressional bills sourced from GovTrack'
    )
    op.create_index(op.f('ix_government_bills_bill_number'), 'government_bills', ['bill_number'], unique=False)
    op.create_index(op.f('ix_government_bills_bill_type'), 'government_bills', ['bill_type'], unique=False)
    op.create_index(op.f('ix_government_bills_chamber'), 'government_bills', ['chamber'], unique=False)
    op.create_index(op.f('ix_government_bills_congress_number'), 'government_bills', ['congress_number'], unique=False)
    op.create_index(op.f('ix_government_bills_country'), 'government_bills', ['country'], unique=False)
    op.create_index(op.f('ix_government_bills_id'), 'government_bills', ['id'], unique=False)
    op.create_index(op.f('ix_government_bills_introduced_at'), 'government_bills', ['introduced_at'], unique=False)
    op.create_index(op.f('ix_government_bills_last_action_at'), 'government_bills', ['last_action_at'], unique=False)
    op.create_index(op.f('ix_government_bills_policy_area'), 'government_bills', ['policy_area'], unique=False)
    op.create_index(op.f('ix_government_bills_sponsor_bioguide_id'), 'government_bills', ['sponsor_bioguide_id'], unique=False)
    op.create_index(op.f('ix_government_bills_sponsor_party'), 'government_bills', ['sponsor_party'], unique=False)
    op.create_index(op.f('ix_government_bills_sponsor_state'), 'government_bills', ['sponsor_state'], unique=False)
    op.create_index(op.f('ix_government_bills_status'), 'government_bills', ['status'], unique=False)
    op.create_index(op.f('ix_government_bills_title'), 'government_bills', ['title'], unique=False)
    op.create_table('government_contracts',
    sa.Column('award_id', sa.String(length=100), nullable=False, comment='Unique award ID from USASpending.gov'),
    sa.Column('award_type', sa.String(length=50), nullable=False, comment='Contract, Grant, Loan, Direct Payment'),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False, comment='Total obligated amount in USD'),
    sa.Column('base_amount', sa.Float(), nullable=False, comment='Base contract value before options'),
    sa.Column('potential_amount', sa.Float(), nullable=True, comment='Maximum potential value including all options'),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agency_id', sa.String(length=50), nullable=False),
    sa.Column('agency_name', sa.String(length=500), nullable=False),
    sa.Column('sub_agency_name', sa.String(length=500), nullable=True),
    sa.Column('agency_code', sa.String(length=20), nullable=True),
    sa.Column('recipient_id', sa.String(length=100), nullable=False),
    sa.Column('recipient_name', sa.String(length=500), nullable=False),
    sa.Column('recipient_uei', sa.String(length=20), nullable=True, comment='Unique Entity Identifier — replaced DUNS in 2022'),
    sa.Column('parent_recipient_name', sa.String(length=500), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True, comment='Stock ticker if recipient is publicly traded'),
    sa.Column('recipient_country', sa.String(length=2), nullable=False),
    sa.Column('recipient_state', sa.String(length=2), nullable=True),
    sa.Column('congressional_district', sa.String(length=10), nullable=True, comment='Links spending to congressional districts and legislators'),
    sa.Column('place_of_performance', sa.String(length=500), nullable=True),
    sa.Column('naics_code', sa.String(length=10), nullable=True),
    sa.Column('naics_description', sa.String(length=500), nullable=True),
    sa.Column('psc_code', sa.String(length=10), nullable=True, comment='Product Service Code — what was purchased'),
    sa.Column('psc_description', sa.String(length=500), nullable=True),
    sa.Column('is_compete', sa.Boolean(), nullable=False, comment='Whether contract was competitively bid'),
    sa.Column('number_of_offers', sa.Integer(), nullable=True, comment='Number of companies that bid'),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True, comment='Original USASpending.gov API response'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Federal contract awards from USASpending.gov'
    )
    op.create_index(op.f('ix_government_contracts_agency_id'), 'government_contracts', ['agency_id'], unique=False)
    op.create_index(op.f('ix_government_contracts_agency_name'), 'government_contracts', ['agency_name'], unique=False)
    op.create_index(op.f('ix_government_contracts_award_id'), 'government_contracts', ['award_id'], unique=True)
    op.create_index(op.f('ix_government_contracts_award_type'), 'government_contracts', ['award_type'], unique=False)
    op.create_index(op.f('ix_government_contracts_congressional_district'), 'government_contracts', ['congressional_district'], unique=False)
    op.create_index(op.f('ix_government_contracts_country'), 'government_contracts', ['country'], unique=False)
    op.create_index(op.f('ix_government_contracts_id'), 'government_contracts', ['id'], unique=False)
    op.create_index(op.f('ix_government_contracts_is_compete'), 'government_contracts', ['is_compete'], unique=False)
    op.create_index(op.f('ix_government_contracts_naics_code'), 'government_contracts', ['naics_code'], unique=False)
    op.create_index(op.f('ix_government_contracts_parent_recipient_name'), 'government_contracts', ['parent_recipient_name'], unique=False)
    op.create_index(op.f('ix_government_contracts_psc_code'), 'government_contracts', ['psc_code'], unique=False)
    op.create_index(op.f('ix_government_contracts_recipient_country'), 'government_contracts', ['recipient_country'], unique=False)
    op.create_index(op.f('ix_government_contracts_recipient_id'), 'government_contracts', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_government_contracts_recipient_name'), 'government_contracts', ['recipient_name'], unique=False)
    op.create_index(op.f('ix_government_contracts_recipient_state'), 'government_contracts', ['recipient_state'], unique=False)
    op.create_index(op.f('ix_government_contracts_recipient_uei'), 'government_contracts', ['recipient_uei'], unique=False)
    op.create_index(op.f('ix_government_contracts_signed_date'), 'government_contracts', ['signed_date'], unique=False)
    op.create_index(op.f('ix_government_contracts_start_date'), 'government_contracts', ['start_date'], unique=False)
    op.create_index(op.f('ix_government_contracts_ticker'), 'government_contracts', ['ticker'], unique=False)
    op.create_index(op.f('ix_government_contracts_total_amount'), 'government_contracts', ['total_amount'], unique=False)
    op.create_table('government_filings',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('filing_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('accession_number', sa.String(length=25), nullable=True),
    sa.Column('company_name', sa.String(length=500), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('period_of_report', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_amendment', sa.Boolean(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True, comment='Original API response — kept for debugging and reprocessing'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_filings_accession_number'), 'government_filings', ['accession_number'], unique=True)
    op.create_index(op.f('ix_government_filings_cik'), 'government_filings', ['cik'], unique=False)
    op.create_index(op.f('ix_government_filings_company_name'), 'government_filings', ['company_name'], unique=False)
    op.create_index(op.f('ix_government_filings_country'), 'government_filings', ['country'], unique=False)
    op.create_index(op.f('ix_government_filings_filed_at'), 'government_filings', ['filed_at'], unique=False)
    op.create_index(op.f('ix_government_filings_filing_type'), 'government_filings', ['filing_type'], unique=False)
    op.create_index(op.f('ix_government_filings_id'), 'government_filings', ['id'], unique=False)
    op.create_index(op.f('ix_government_filings_region'), 'government_filings', ['region'], unique=False)
    op.create_index(op.f('ix_government_filings_source'), 'government_filings', ['source'], unique=False)
    op.create_index(op.f('ix_government_filings_status'), 'government_filings', ['status'], unique=False)
    op.create_index(op.f('ix_government_filings_ticker'), 'government_filings', ['ticker'], unique=False)
    op.create_index(op.f('ix_government_filings_title'), 'government_filings', ['title'], unique=False)
    op.create_table('government_lobbying',
    sa.Column('filing_id', sa.String(length=100), nullable=False, comment='Unique filing ID from OpenSecrets'),
    sa.Column('filing_type', sa.String(length=20), nullable=False, comment='Q1, Q2, Q3, Q4, Mid-Year, Year-End'),
    sa.Column('filing_year', sa.Integer(), nullable=False),
    sa.Column('filing_period', sa.String(length=20), nullable=False, comment='e.g. 2024 Q1, 2024 Mid-Year'),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False, comment='Total lobbying spend in USD for this period'),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('client_name', sa.String(length=500), nullable=False),
    sa.Column('client_industry', sa.String(length=100), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True, comment='Stock ticker if client is publicly traded'),
    sa.Column('registrant_id', sa.String(length=100), nullable=False),
    sa.Column('registrant_name', sa.String(length=500), nullable=False),
    sa.Column('client_country', sa.String(length=2), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('lobbyists', sa.JSON(), nullable=True, comment='Individual lobbyists working this filing'),
    sa.Column('issues', sa.JSON(), nullable=True, comment='Specific issues and bills being lobbied on'),
    sa.Column('has_former_government', sa.Boolean(), nullable=False, comment='True if any lobbyist is a former government official'),
    sa.Column('yoy_change', sa.Float(), nullable=True, comment='Year over year spend change as percentage'),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True, comment='Original OpenSecrets API response'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Lobbying disclosures from OpenSecrets'
    )
    op.create_index(op.f('ix_government_lobbying_amount'), 'government_lobbying', ['amount'], unique=False)
    op.create_index(op.f('ix_government_lobbying_client_country'), 'government_lobbying', ['client_country'], unique=False)
    op.create_index(op.f('ix_government_lobbying_client_id'), 'government_lobbying', ['client_id'], unique=False)
    op.create_index(op.f('ix_government_lobbying_client_industry'), 'government_lobbying', ['client_industry'], unique=False)
    op.create_index(op.f('ix_government_lobbying_client_name'), 'government_lobbying', ['client_name'], unique=False)
    op.create_index(op.f('ix_government_lobbying_country'), 'government_lobbying', ['country'], unique=False)
    op.create_index(op.f('ix_government_lobbying_filed_at'), 'government_lobbying', ['filed_at'], unique=False)
    op.create_index(op.f('ix_government_lobbying_filing_id'), 'government_lobbying', ['filing_id'], unique=True)
    op.create_index(op.f('ix_government_lobbying_filing_type'), 'government_lobbying', ['filing_type'], unique=False)
    op.create_index(op.f('ix_government_lobbying_filing_year'), 'government_lobbying', ['filing_year'], unique=False)
    op.create_index(op.f('ix_government_lobbying_has_former_government'), 'government_lobbying', ['has_former_government'], unique=False)
    op.create_index(op.f('ix_government_lobbying_id'), 'government_lobbying', ['id'], unique=False)
    op.create_index(op.f('ix_government_lobbying_registrant_id'), 'government_lobbying', ['registrant_id'], unique=False)
    op.create_index(op.f('ix_government_lobbying_registrant_name'), 'government_lobbying', ['registrant_name'], unique=False)
    op.create_index(op.f('ix_government_lobbying_ticker'), 'government_lobbying', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_government_lobbying_ticker'), table_name='government_lobbying')
    op.drop_index(op.f('ix_government_lobbying_registrant_name'), table_name='government_lobbying')
    op.drop_index(op.f('ix_government_lobbying_registrant_id'), table_name='government_lobbying')
    op.drop_index(op.f('ix_government_lobbying_id'), table_name='government_lobbying')
    op.drop_index(op.f('ix_government_lobbying_has_former_government'), table_name='government_lobbying')
    op.drop_index(op.f('ix_government_lobbying_filing_year'), table_name='government_lobbying')
    op.drop_index(op.f('ix_government_lobbying_filing_type'), table_name='government_lobbying')
    op.drop_index(op.f('ix_government_lobbying_filing_id'), table_name='government_lobbying')
    op.drop_index(op.f('ix_government_lobbying_filed_at'), table_name='government_lobbying')
    op.drop_index(op.f('ix_government_lobbying_country'), table_name='government_lobbying')
    op.drop_index(op.f('ix_government_lobbying_client_name'), table_name='government_lobbying')
    op.drop_index(op.f('ix_government_lobbying_client_industry'), table_name='government_lobbying')
    op.drop_index(op.f('ix_government_lobbying_client_id'), table_name='government_lobbying')
    op.drop_index(op.f('ix_government_lobbying_client_country'), table_name='government_lobbying')
    op.drop_index(op.f('ix_government_lobbying_amount'), table_name='government_lobbying')
    op.drop_table('government_lobbying')
    op.drop_index(op.f('ix_government_filings_title'), table_name='government_filings')
    op.drop_index(op.f('ix_government_filings_ticker'), table_name='government_filings')
    op.drop_index(op.f('ix_government_filings_status'), table_name='government_filings')
    op.drop_index(op.f('ix_government_filings_source'), table_name='government_filings')
    op.drop_index(op.f('ix_government_filings_region'), table_name='government_filings')
    op.drop_index(op.f('ix_government_filings_id'), table_name='government_filings')
    op.drop_index(op.f('ix_government_filings_filing_type'), table_name='government_filings')
    op.drop_index(op.f('ix_government_filings_filed_at'), table_name='government_filings')
    op.drop_index(op.f('ix_government_filings_country'), table_name='government_filings')
    op.drop_index(op.f('ix_government_filings_company_name'), table_name='government_filings')
    op.drop_index(op.f('ix_government_filings_cik'), table_name='government_filings')
    op.drop_index(op.f('ix_government_filings_accession_number'), table_name='government_filings')
    op.drop_table('government_filings')
    op.drop_index(op.f('ix_government_contracts_total_amount'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_ticker'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_start_date'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_signed_date'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_recipient_uei'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_recipient_state'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_recipient_name'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_recipient_id'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_recipient_country'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_psc_code'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_parent_recipient_name'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_naics_code'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_is_compete'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_id'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_country'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_congressional_district'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_award_type'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_award_id'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_agency_name'), table_name='government_contracts')
    op.drop_index(op.f('ix_government_contracts_agency_id'), table_name='government_contracts')
    op.drop_table('government_contracts')
    op.drop_index(op.f('ix_government_bills_title'), table_name='government_bills')
    op.drop_index(op.f('ix_government_bills_status'), table_name='government_bills')
    op.drop_index(op.f('ix_government_bills_sponsor_state'), table_name='government_bills')
    op.drop_index(op.f('ix_government_bills_sponsor_party'), table_name='government_bills')
    op.drop_index(op.f('ix_government_bills_sponsor_bioguide_id'), table_name='government_bills')
    op.drop_index(op.f('ix_government_bills_policy_area'), table_name='government_bills')
    op.drop_index(op.f('ix_government_bills_last_action_at'), table_name='government_bills')
    op.drop_index(op.f('ix_government_bills_introduced_at'), table_name='government_bills')
    op.drop_index(op.f('ix_government_bills_id'), table_name='government_bills')
    op.drop_index(op.f('ix_government_bills_country'), table_name='government_bills')
    op.drop_index(op.f('ix_government_bills_congress_number'), table_name='government_bills')
    op.drop_index(op.f('ix_government_bills_chamber'), table_name='government_bills')
    op.drop_index(op.f('ix_government_bills_bill_type'), table_name='government_bills')
    op.drop_index(op.f('ix_government_bills_bill_number'), table_name='government_bills')
    op.drop_table('government_bills')
    # ### end Alembic commands ###